### ISSUE TITLE
This notebook is the solution to homework 4

### ISSUE THREAD

**Issue by UpperLeftHandSide** [JoeDumoulin/CSCD496S19#8]

**Comment by UpperLeftHandSide** [comment]
Notebooks/Neural Networks with Convolutional Layers/Convolutional Network Example for MNIST.ipynb

**Comment by JoeDumoulin** [comment]
It is one solution.  There are many solutions to this problem on the internet.  I put this up mostly to give examples of how to print the internals of the convolutional network during evaluation.

**Comment by UpperLeftHandSide** [comment]
None of the networks in that notebook are convolutional.

**Comment by JoeDumoulin** [comment]
Got it.  It should be fixed now.  take a look.

**Comment by UpperLeftHandSide** [comment]
Awesome, thanks.
